# Generated by Django 3.2.13 on 2022-09-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220831_1348'),
        ('articles', '0002_auto_20220831_2123'),
    ]

    operations = [
    ]
